### ISSUE TITLE
بررسی مقادیر فایل env

### ISSUE THREAD

**Issue by BaseMax** [BaseMax/GoTODORest#1]
Max Base, [3/28/2023 10:12 AM]
  if err := godotenv.Load("development.env"); err != nil {
    log.Fatal("Error while loading .env file!")
  }

  // mysql database config
  cfg := mysql.Config{
    User:                 os.Getenv("DBUSER"),
    Passwd:               os.Getenv("DBPASS"),
    Net:                  os.Getenv("NET"),
    Addr:                 os.Getenv("ADDR"),
    DBName:               os.Getenv("DBNAME"),
    AllowNativePasswords: true,
  }

Max Base, [3/28/2023 10:13 AM]
بنظرم بعد از لو دچک کنید که اون مقادیر حتما وجود داشته باشند.

Max Base, [3/28/2023 10:13 AM]
چون الان هیچ اعتبارسنجی و بررسی روی مقادیر انجام ندادید.

**Comment by MaxianEdison** [comment]
تغییرات زیر رو در کد انجام دادم برای حل این مشکل: 
```
if !isEnvExit("DBUSER", "DBPASS", "NET", "ADDR", "DBNAME") {
	log.Fatal("environment variable must exit!")
}


func isEnvExit(keys ...string) bool {
	var is bool = false
	for _, key := range keys {
		if _, ok := os.LookupEnv(key); ok {
			is = true
		} else {
			is = false
			return is
		}
	}
	return is
}
```

**Comment by BaseMax** [comment]
سپاس
